name: Kernel Builder

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-kernel:
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4
      with:
        repository: secretgogeta-kernels/android_kernel_oneplus_sm6375
        path: kernel

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential libssl-dev libncurses-dev \
          bison flex bc rsync kmod cpio python3 \
          clang llvm lld libelf-dev git wget

    - name: Download Config
      run: |
        wget https://github.com/secretgogeta-kernels/android_kernel_oneplus_sm6375/releases/download/A/config.gz -O kernel/config.gz
        gunzip -c kernel/config.gz > kernel/.config

    - name: Setup Toolchains
      run: |
        # Install GCC
        git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-gnu-9.3 kernel/gcc
        
        # Install Clang
        wget https://github.com/ZyCromerZ/Clang/releases/download/21.0.0git-20250617-release/Clang-21.0.0git-20250617.tar.gz
        tar -xzf Clang-21.0.0git-20250617.tar.gz
        mv Clang-21.0.0git-20250617 kernel/clang
        rm Clang-21.0.0git-20250617.tar.gz

    - name: Debugging with tmate
      # You may pin to the exact commit or the version.
      # uses: mxschmitt/action-tmate@7b6a61a73bbb9793cb80ad69b8dd8ac19261834c
      uses: mxschmitt/action-tmate@v3.22
      
    - name: Prepare Build Environment
      run: |
        cd kernel
        make ARCH=arm64 O=out CC=$(pwd)/clang/bin/clang \
            CROSS_COMPILE=$(pwd)/gcc/bin/aarch64-linux-gnu- \
            oldconfig </dev/null

    - name: Build Kernel
      run: |
        cd kernel
        make -j$(nproc) ARCH=arm64 O=out CC=$(pwd)/clang/bin/clang \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=$(pwd)/gcc/bin/aarch64-linux-gnu- \
            LD=ld.lld \
            LLVM=1 \
            LLVM_IAS=1

    - name: Setup AnyKernel3
      run: |
        git clone https://github.com/osm0sis/AnyKernel3
        cp kernel/out/arch/arm64/boot/Image.gz AnyKernel3/
        mkdir -p AnyKernel3/dtbs
        cp kernel/out/arch/arm64/boot/dts/vendor/*.dtb AnyKernel3/dtbs/

    - name: Create Flashable Zip
      run: |
        cd AnyKernel3
        zip -r9 kernel.zip *
        mv kernel.zip ../

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: kernel-build
        path: |
          kernel.zip
          kernel/out/arch/arm64/boot/Image.gz
