name: Kernel Builder

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev \
          libc6-dev-i386 x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev \
          libxml2-utils xsltproc unzip fontconfig repo libssl-dev android-sdk-platform-tools

    - name: Clone repositories
      run: |
        git clone --depth 1 https://github.com/LineageOS/android_kernel_oneplus_sm6375
        git clone --depth 1 https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b
        git clone --depth 1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9
        git clone --depth 1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9

    - name: Download config
      run: |
        wget https://github.com/secretgogeta-kernels/android_kernel_oneplus_sm6375/releases/download/A/config.gz
        zcat config.gz > larry_defconfig
        
        # Fix section mismatch errors by allowing warnings only
        echo "CONFIG_SECTION_MISMATCH_WARN_ONLY=y" >> larry_defconfig
        
        mv larry_defconfig android_kernel_oneplus_sm6375/arch/arm64/configs/

    - name: Set up build environment
      run: |
        echo "CLANG_DIR=$PWD/android_prebuilts_clang_kernel_linux-x86_clang-r416183b/bin" >> $GITHUB_ENV
        echo "GCC64_DIR=$PWD/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9/bin" >> $GITHUB_ENV
        echo "GCC_DIR=$PWD/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9/bin" >> $GITHUB_ENV

    - name: Build kernel
      run: |
        cd android_kernel_oneplus_sm6375
        make O=out ARCH=arm64 mrproper
        
        # Configure kernel with automatic defaults
        make O=out ARCH=arm64 larry_defconfig
        make O=out ARCH=arm64 olddefconfig
        
        # Build with section mismatch warnings allowed
        make -j$(nproc --all) \
          PATH="$CLANG_DIR:$GCC64_DIR:$GCC_DIR:$PATH" \
          CC=clang \
          CLANG_TRIPLE=aarch64-linux-gnu- \
          CROSS_COMPILE=aarch64-linux-android- \
          CROSS_COMPILE_ARM32=arm-linux-androideabi- \
          O=out \
          ARCH=arm64

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-build
        path: |
          android_kernel_oneplus_sm6375/out/arch/arm64/boot/Image.gz
          android_kernel_oneplus_sm6375/out/arch/arm64/boot/dtbo.img
          android_kernel_oneplus_sm6375/out/arch/arm64/boot/dtb.img
