name: Trigger Kernel Build

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI
  push:               # Optional: Trigger on push to specific branches
    branches:
      - main
  pull_request:       # Optional: Trigger on pull requests
    branches:
      - main

jobs:
  trigger-kernel-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Kernel Build
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build.yml',  # Name of your build workflow file
              ref: 'main',               # Branch where build workflow is located
              inputs: {
                model: 'OPAce5Pro',
                soc: 'sun',
                branch: 'default',        # Now using default branch
                manifest: 'default.xml',   # Placeholder (not used in new setup)
                android_version: '14',
                kernel_version: '5.15',
                ksun_branch: 'stable'
              }
            });
